# Generated by Django 2.1 on 2018-08-31 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='书名')),
                ('authors', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('status', models.CharField(choices=[('in', '在库'), ('out', '出库')], max_length=5, verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类名')),
                ('root', models.CharField(max_length=50, verbose_name='房间')),
                ('site', models.CharField(max_length=50, verbose_name='书架')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='分类'),
        ),
    ]
