# Generated by Django 2.1 on 2018-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180831_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': '借阅记录', 'verbose_name_plural': '借阅记录'},
        ),
        migrations.AddField(
            model_name='borrow',
            name='back_time',
            field=models.DateField(null=True, verbose_name='还书时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='借阅时间'),
        ),
    ]
