# Generated by Django 2.1 on 2018-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='back_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='还书时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='毕业日期'),
        ),
    ]
